/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("java")
    id("application")
    id("edu.sc.seis.launch4j") version "4.0.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // MySQL Connector JAR dependency
    implementation("com.mysql:mysql-connector-j:8.4.0")

    // FlatLaf for modern Swing look and feel
    implementation("com.formdev:flatlaf:3.4.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass.set("MainSystem.Main")
}

// Configure Launch4j
launch4j {
    mainClassName.set("MainSystem.Main")
    outfile.set("Project4.exe")
    
    // Set to "gui" to hide the background console window for Swing apps
    headerType.set("gui") 
    
    // JVM Settings
    jreMinVersion.set("21") // Adjust to match your target Java version
    
    // Error handling properties
    windowTitle.set("Project4 System")
    errTitle.set("Application Launch Error")
    // customProcName.set(true)
    
    // Optional: Include bundled JRE path if you plan to ship Java with your app
    // bundledJrePath.set("jre") 
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
