package FrameSystem.Modules.Login;

import FrameSystem.SLibrary.Panel.SPanel;

/**
 *
 * @author SPPR-LOQ
 */
public class ModuleLogin extends SPanel{

    /**
     * Creates new form ModuleLogin
     */
    public ModuleLogin(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sPanel1 = new FrameSystem.SLibrary.Panel.SPanel();

        setBackground(new java.awt.Color(255, 209, 209));
        setBorderBottomLeftRadius(20);
        setBorderBottomRightRadius(20);
        setBorderTopLeftRadius(20);
        setBorderTopRightRadius(20);
        setBoxShadow(true);
        setBoxShadowBlur(5);
        setBoxShadowColor(new java.awt.Color(204, 204, 204));
        setBoxShadowOffsetY(0);
        setBoxShadowOpacity(0.05F);
        setDisplay(FrameSystem.SLibrary.Panel.SPanel.Display.FLEX);
        setAlignItems(FrameSystem.SLibrary.Panel.SPanel.AlignItems.STRETCH);
        setJustifyContent(FrameSystem.SLibrary.Panel.SPanel.JustifyContent.FLEX_END);
        setPreferredSize(new java.awt.Dimension(875, 579));

        sPanel1.setBackground(new java.awt.Color(255, 243, 243));
        sPanel1.setBorderBottomLeftRadius(20);
        sPanel1.setBorderBottomRightRadius(20);
        sPanel1.setBorderTopLeftRadius(20);
        sPanel1.setBorderTopRightRadius(20);
        sPanel1.setPreferredSize(new java.awt.Dimension(555, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(sPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FrameSystem.SLibrary.Panel.SPanel sPanel1;
    // End of variables declaration//GEN-END:variables
}
